name: Build App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x64, x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build Electron App for x64
        if: ${{ matrix.architecture == 'x64' }}
        run: |
          npm run build --win --x64

      - name: Build Electron App for ia32
        if: ${{ matrix.architecture == 'x86' }}
        run: |
          npm run build --win --ia32

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-browser-app-windows-${{ matrix.architecture }}
          path: dist/*
