name: Build App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x64, ia32]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build Electron App
        run: |
          npm run build --win --${{ matrix.architecture }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-browser-app-windows-${{ matrix.architecture }}
          path: dist/*
